name: SmartiecoinWallet
options:
  bundleIdPrefix: com.smartiecoin
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  secp256k1:
    url: https://github.com/GigaBitcoin/secp256k1.swift
    exactVersion: "0.10.0"

targets:
  SmartiecoinNode:
    type: application
    platform: iOS
    sources:
      - path: SmartiecoinWallet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.smartiecoin.node
        PRODUCT_NAME: "SMT Node"
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: SmartiecoinWallet/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: true
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "WALLET_MODE_SPV"
    dependencies:
      - package: secp256k1

  SmartiecoinLite:
    type: application
    platform: iOS
    sources:
      - path: SmartiecoinWallet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.smartiecoin.lite
        PRODUCT_NAME: "SMT Lite"
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: SmartiecoinWallet/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: true
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "WALLET_MODE_API"
    dependencies:
      - package: secp256k1
